// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoWong.Data;

#nullable disable

namespace ProyectoWong.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831042735_AjusteRelacionesRecepcion")]
    partial class AjusteRelacionesRecepcion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoWong.Models.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCaducidad")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("MaximoInventario")
                        .HasColumnType("int");

                    b.Property<int>("MinimoInventario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroLote")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroPieza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Componentes");
                });

            modelBuilder.Entity("ProyectoWong.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.InspeccionQA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CertificadoDisponible")
                        .HasColumnType("bit");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EmpaqueOk")
                        .HasColumnType("bit");

                    b.Property<bool>("EtiquetaOk")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInspeccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspeccionadoPor")
                        .HasColumnType("int");

                    b.Property<bool>("MaterialOk")
                        .HasColumnType("bit");

                    b.Property<int>("RecepcionDetalleId")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionadoPor");

                    b.HasIndex("RecepcionDetalleId")
                        .IsUnique();

                    b.ToTable("InspeccionesQA");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("PalletId")
                        .HasColumnType("int");

                    b.Property<int>("RealizadoPor")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.HasIndex("RealizadoPor");

                    b.HasIndex("UbicacionId");

                    b.HasIndex("UbicacionId1");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.OrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEsperada")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroOC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Proveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrdenesCompra");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.OrdenCompraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadEsperada")
                        .HasColumnType("int");

                    b.Property<int>("ComponenteId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenCmpraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteId");

                    b.HasIndex("OrdenCmpraId");

                    b.ToTable("OrdenCompraDetalles");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.Pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPallet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaImpresionEtiqueta")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecepcionDetalleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecepcionDetalleId");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.Recepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrdenCompraId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recepciones");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.RecepcionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadRecibida")
                        .HasColumnType("int");

                    b.Property<int>("ComponenteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaCaducidad")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RecepcionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteId");

                    b.HasIndex("RecepcionId");

                    b.ToTable("RecepcionDetalles");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Zona")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("ProyectoWong.Models.Usuarios", b =>
                {
                    b.Property<int>("ExpUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpUsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpUsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.InspeccionQA", b =>
                {
                    b.HasOne("ProyectoWong.Models.Usuarios", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspeccionadoPor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProyectoWong.Models.Recepcion.RecepcionDetalle", "RecepcionDetalle")
                        .WithOne("Inspeccion")
                        .HasForeignKey("ProyectoWong.Models.Recepcion.InspeccionQA", "RecepcionDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspector");

                    b.Navigation("RecepcionDetalle");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.MovimientoInventario", b =>
                {
                    b.HasOne("ProyectoWong.Models.Recepcion.Pallet", "Pallet")
                        .WithMany("Movimientos")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoWong.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("RealizadoPor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProyectoWong.Models.Recepcion.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoWong.Models.Recepcion.Ubicacion", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("UbicacionId1");

                    b.Navigation("Pallet");

                    b.Navigation("Ubicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.OrdenCompraDetalle", b =>
                {
                    b.HasOne("ProyectoWong.Models.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoWong.Models.Recepcion.OrdenCompra", "OrdenCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenCmpraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Componente");

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.Pallet", b =>
                {
                    b.HasOne("ProyectoWong.Models.Recepcion.RecepcionDetalle", "RecepcionDetalle")
                        .WithMany("Pallets")
                        .HasForeignKey("RecepcionDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecepcionDetalle");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.Recepcion", b =>
                {
                    b.HasOne("ProyectoWong.Models.Recepcion.OrdenCompra", "OrdenCompra")
                        .WithMany("Recepciones")
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoWong.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrdenCompra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.RecepcionDetalle", b =>
                {
                    b.HasOne("ProyectoWong.Models.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoWong.Models.Recepcion.Recepcion", "Recepcion")
                        .WithMany("Detalles")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Componente");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Recepciones");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.Pallet", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.Recepcion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.RecepcionDetalle", b =>
                {
                    b.Navigation("Inspeccion");

                    b.Navigation("Pallets");
                });

            modelBuilder.Entity("ProyectoWong.Models.Recepcion.Ubicacion", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
